# Example values for pipeops-gateway

environment:
  mode: single-vm
  vmIP: 203.0.113.10

istio:
  enabled: true
  gateway:
    selector:
      istio: ingressgateway
    servers:
      - port:
          number: 6379
          name: tcp-redis
          protocol: TCP
  virtualService:
    tcpRoutes:
      - name: redis
        port: 6379
        destination:
          host: redis.default.svc.cluster.local
          port: 6379
  service:
    create: true
    namespace: istio-system

# Uncomment for Gateway API example
# gatewayApi:
#   enabled: true
#   gateway:
#     gatewayClassName: istio
#     listeners:
#       - name: tcp-redis
#         port: 6379
#         protocol: TCP
#   tcpRoutes:
#     - name: redis
#       sectionName: tcp-redis
#       backendRefs:
#         - name: redis
#           namespace: default
#           port: 6379

