# Default ClusterIssuers for PipeOps cert-manager integration
# These are automatically created when cert-manager is installed by the agent
# You can also apply them manually with: kubectl apply -f cert-manager-clusterissuers.yaml

---
# ClusterIssuer for Let's Encrypt production
# Use annotation: cert-manager.io/cluster-issuer: "letsencrypt-prod"
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production Let's Encrypt ACME server
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email for Let's Encrypt notifications (certificate expiry, etc.)
    # TODO: Update this with your actual admin email
    email: admin@pipeops.io
    
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # HTTP-01 challenge solver using NGINX Ingress Controller
    solvers:
    - http01:
        ingress:
          class: nginx

---
# ClusterIssuer for Let's Encrypt production (alias)
# Use annotation: cert-manager.io/cluster-issuer: "letsencrypt-production"
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # Production Let's Encrypt ACME server
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email for Let's Encrypt notifications
    # TODO: Update this with your actual admin email
    email: admin@pipeops.io
    
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    
    # HTTP-01 challenge solver using NGINX Ingress Controller
    solvers:
    - http01:
        ingress:
          class: nginx

---
# Optional: ClusterIssuer for Let's Encrypt staging (for testing)
# Use annotation: cert-manager.io/cluster-issuer: "letsencrypt-staging"
# Uncomment to enable:
#
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
# spec:
#   acme:
#     # Staging Let's Encrypt ACME server (use for testing)
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     
#     email: admin@pipeops.io
#     
#     privateKeySecretRef:
#       name: letsencrypt-staging
#     
#     solvers:
#     - http01:
#         ingress:
#           class: nginx
