apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeops-agent
  namespace: pipeops-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeops-agent
rules:
# Core resources
- apiGroups: [""]
  resources: 
    - "nodes"
    - "pods"
    - "namespaces"
    - "services"
    - "configmaps"
    - "secrets"
    - "serviceaccounts"
    - "persistentvolumes"
    - "persistentvolumeclaims"
    - "endpoints"
    - "events"
    - "resourcequotas"
    - "limitranges"
    - "replicationcontrollers"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Apps resources
- apiGroups: ["apps"]
  resources: 
    - "deployments"
    - "statefulsets"
    - "daemonsets"
    - "replicasets"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Batch jobs
- apiGroups: ["batch"]
  resources: 
    - "jobs"
    - "cronjobs"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Networking
- apiGroups: ["networking.k8s.io"]
  resources: 
    - "ingresses"
    - "networkpolicies"
    - "ingressclasses"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# RBAC
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: 
    - "roles"
    - "rolebindings"
    - "clusterroles"
    - "clusterrolebindings"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "bind", "escalate"]

# Autoscaling
- apiGroups: ["autoscaling"]
  resources:
    - "horizontalpodautoscalers"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Admission webhooks
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
    - "mutatingwebhookconfigurations"
    - "validatingwebhookconfigurations"
  verbs: ["get", "list", "watch", "create", "update", "patch"]

# API registration (metrics API)
- apiGroups: ["apiregistration.k8s.io"]
  resources:
    - "apiservices"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Certificates
- apiGroups: ["certificates.k8s.io"]
  resources:
    - "certificatesigningrequests"
  verbs: ["get", "list", "watch"]

# Custom resource definitions
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - "customresourcedefinitions"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Coordination (leases)
- apiGroups: ["coordination.k8s.io"]
  resources:
    - "leases"
  verbs: ["get", "list", "watch"]

# Policy
- apiGroups: ["policy"]
  resources:
    - "poddisruptionbudgets"
    - "podsecuritypolicies"
  verbs: ["get", "list", "watch", "use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeops-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # Using built-in cluster-admin role for full access
subjects:
- kind: ServiceAccount
  name: pipeops-agent
  namespace: pipeops-system
