apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeops-agent-config
  namespace: pipeops-system
data:
  config.yaml: |
    agent:
      id: ""
      name: "minikube-test-cluster"
      cluster_name: "minikube-test-cluster"
      grafana_sub_path: false
      labels:
        environment: "development"
        region: "minikube"
    
    pipeops:
      api_url: "http://host.docker.internal:8002"
      token: "sat_77m2cb45zmc4yexa3ddisjhbr3hg5sx6"  # Re
      timeout: "30s"
      reconnect:
        enabled: true
        max_attempts: 3
        interval: "5s"
        backoff: "5s"
      tls:
        enabled: true
        insecure_skip_verify: false
    
    tunnel:
      enabled: true
      inactivity_timeout: "5m"
    
    kubernetes:
      kubeconfig: ""
      in_cluster: true
      namespace: "pipeops-system"
    
    logging:
      level: "debug"
      format: "json"
      output: "stdout"

---
# NOTE: The pipeops-agent-state ConfigMap is automatically created and managed
# by the agent at runtime. Do not define it here as it would reset the state
# on every kubectl apply, causing the agent to lose its identity.
