apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeops-agent-config
  namespace: pipeops-system
data:
  config.yaml: |
    agent:
      id: ""
      name: "minikube-test-cluster"
      cluster_name: "minikube-test-cluster"
      labels:
        environment: "development"
        region: "minikube"
    
    pipeops:
      api_url: "https://api.pipeops.sh"
      token: "sat_k5opsiklk6x4llu2vfik2izmxnjbnvxg"
      timeout: "30s"
      reconnect:
        enabled: true
        max_attempts: 3
        interval: "5s"
        backoff: "5s"
      tls:
        enabled: true
        insecure_skip_verify: false
    
    tunnel:
      enabled: true
      inactivity_timeout: "5m"
    
    kubernetes:
      kubeconfig: ""
      in_cluster: true
      namespace: "pipeops-system"
    
    logging:
      level: "debug"
      format: "json"
      output: "stdout"

---
# State ConfigMap - persists agent state across pod restarts  
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeops-agent-state
  namespace: pipeops-system
  labels:
    app: pipeops-agent
    component: state
data:
  agent_id: ""
  cluster_id: ""
  cluster_token: ""
