# Test Configuration for PipeOps Agent
# Points to local mock servers for testing

agent:
  id: "test-agent-001"
  name: "test-pipeops-agent"
  cluster_name: "test-cluster"
  poll_interval: "10s"
  labels:
    environment: "test"
    region: "local"

pipeops:
  # Point to mock Control Plane
  control_plane_url: "ws://localhost:8081/ws"
  token: "test-control-plane-token"
  
  capabilities:
    - "deploy"
    - "scale" 
    - "delete"
    - "logs"
    - "exec"
    - "metrics"
  
  timeout: "30s"
  
  reconnect:
    max_retries: 5
    initial_delay: "2s"
    max_delay: "30s"

server:
  port: 8080
  host: "0.0.0.0"
  
  # Allow all origins for testing
  cors:
    enabled: true
    allowed_origins: ["*"]

kubernetes:
  config_path: "" # Use in-cluster config
  context: ""
  
tls:
  enabled: false # Disable TLS for local testing

logging:
  level: "debug"
  format: "text"
