agent:
  id: ""
  name: "test-agent-1760433326-19123"
  cluster_name: "test-cluster-1760433326-19123"
  poll_interval: "30s"
  labels:
    environment: "test"
    region: "local"
    test: "true"

pipeops:
  api_url: "https://api.pipeops.sh"
  token: "clt_ptilo3ycbhsxmou63m6mzo2qma3aufgp"
  timeout: "30s"
  reconnect:
    enabled: true
    max_attempts: 3
    interval: "5s"
    backoff: "5s"
  tls:
    enabled: true
    insecure_skip_verify: false

tunnel:
  enabled: false

kubernetes:
  kubeconfig: ""
  in_cluster: false
  namespace: "pipeops-system"

logging:
  level: "debug"
  format: "text"
  output: "stdout"
