# PipeOps Agent Configuration - Local Development
# Simple config for testing agent registration without tunnel

agent:
  id: ""
  name: "nitrocode-macbook-pro"
  cluster_name: "nitrocode-macbook-pro"
  labels:
    environment: "development"
    region: "local"

pipeops:
  api_url: "https://api.pipeops.sh"
  token: "clt_ptilo3ycbhsxmou63m6mzo2qma3aufgp"  # Replace with your actual token
  timeout: "30s"
  reconnect:
    enabled: true
    max_attempts: 3
    interval: "5s"
    backoff: "5s"
  tls:
    enabled: true
    insecure_skip_verify: false

# Tunnel disabled for local testing
tunnel:
  enabled: true
  
  # Inactivity timeout - tunnel closes after this period of no API requests (e.g., "5m", "10m")
  inactivity_timeout: "5m"

kubernetes:
  kubeconfig: ""
  in_cluster: true
  namespace: "pipeops-system"

logging:
  level: "info"
  format: "json"
  output: "stdout"
