apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: pipeops-monitoring
data:
  values.yaml: |
    # Loki Helm Chart Values
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      
    singleBinary:
      replicas: 1
      persistence:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
    
    test:
      enabled: false
