apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values
  namespace: pipeops-monitoring
data:
  values.yaml: |
    # Prometheus Helm Chart Values
    server:
      enabled: true
      persistentVolume:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      service:
        type: ClusterIP
        servicePort: 9090
    
    alertmanager:
      enabled: false
    
    pushgateway:
      enabled: false
    
    kube-state-metrics:
      enabled: true
    
    prometheus-node-exporter:
      enabled: true
