apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipeops-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pipeops-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pipeops-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pipeops-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pipeops-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PIPEOPS_API_URL
              value: {{ .Values.agent.pipeops.apiUrl | quote }}
            - name: PIPEOPS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "pipeops-agent.fullname" . }}-config
                  key: token
            - name: AGENT_CLUSTER_NAME
              value: {{ .Values.agent.cluster.name | quote }}
            {{- if .Values.agent.id }}
            - name: AGENT_ID
              value: {{ .Values.agent.id | quote }}
            {{- end }}
            - name: KUBERNETES_IN_CLUSTER
              value: {{ .Values.agent.kubernetes.inCluster | quote }}
            # FRP Configuration
            - name: FRP_ENABLED
              value: {{ .Values.agent.frp.enabled | quote }}
            - name: FRP_SERVER_HOST
              value: {{ .Values.agent.frp.server.host | quote }}
            - name: FRP_SERVER_PORT
              value: {{ .Values.agent.frp.server.port | quote }}
            - name: FRP_SERVER_URL
              value: {{ .Values.agent.frp.server.url | quote }}
            - name: FRP_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "pipeops-agent.fullname" . }}-config
                  key: frp-server-token
                  optional: true
            - name: FRP_CLIENT_NAME
              value: {{ .Values.agent.frp.client.name | default (printf "%s-%s" (include "pipeops-agent.fullname" .) .Release.Namespace) | quote }}
            - name: FRP_CLIENT_USER
              value: {{ .Values.agent.frp.client.user | quote }}
            - name: FRP_CLIENT_LOG_LEVEL
              value: {{ .Values.agent.frp.client.logLevel | quote }}
            - name: FRP_AUTH_METHOD
              value: {{ .Values.agent.frp.auth.method | quote }}
            - name: FRP_AUTH_TOKEN_ENDPOINT
              value: {{ .Values.agent.frp.auth.tokenEndpoint | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /.cache
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
