{{- if .Values.rbac.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "pipeops-agent.name" . }}
    app.kubernetes.io/component: namespace
    {{- include "pipeops-agent.labels" . | nindent 4 }}
{{- end }}
