{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pipeops-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pipeops-agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "pipeops-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "pipeops-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}