apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipeops-agent.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pipeops-agent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.agent.pipeops.token | b64enc | quote }}
