#!/bin/bash

# Display available features and capabilities

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     PipeOps Intelligent Cluster Installer            ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${GREEN}✨ Key Features:${NC}"
echo ""
echo "  🎯 Intelligent Cluster Detection"
echo "     Automatically analyzes your environment and chooses"
echo "     the best Kubernetes distribution for your system"
echo ""
echo "  🚀 Multi-Cluster Support"
echo "     • k3s - Production-grade (VMs, bare metal, cloud)"
echo "     • minikube - Development (macOS, workstations)"
echo "     • k3d - Fast Docker-based (rapid iteration)"
echo "     • kind - Testing (CI/CD, multi-node)"
echo ""
echo "  📊 Complete Monitoring Stack"
echo "     • Prometheus - Metrics collection"
echo "     • Loki - Log aggregation"
echo "     • Grafana - Visualization"
echo "     • OpenCost - Cost monitoring"
echo ""
echo "  🔍 Smart Environment Detection"
echo "     Detects: Docker, LXC, WSL, macOS, CI/CD"
echo "     Analyzes: CPU, Memory, Disk, Network"
echo ""
echo "  ⚙️  Zero Configuration Required"
echo "     Works out of the box with sensible defaults"
echo "     Manual override available if needed"
echo ""

echo -e "${YELLOW}📖 Quick Start:${NC}"
echo ""
echo "  # Automatic detection (recommended):"
echo "  export PIPEOPS_TOKEN=\"your-token\""
echo "  ./install.sh"
echo ""
echo "  # View system analysis:"
echo "  ./detect-cluster-type.sh info"
echo ""
echo "  # Manual cluster selection:"
echo "  export CLUSTER_TYPE=\"k3d\""
echo "  ./install.sh"
echo ""

echo -e "${GREEN}📚 Documentation:${NC}"
echo ""
echo "  • Complete Guide: docs/INTELLIGENT_CLUSTER_SETUP.md"
echo "  • Changes Log: CHANGES.md"
echo "  • Scripts Guide: scripts/README.md"
echo "  • Examples: scripts/examples/"
echo ""

echo -e "${YELLOW}🧪 Test Detection:${NC}"
echo ""
echo "  Run: ./test-detection.sh"
echo ""

echo -e "${BLUE}💡 Example Scenarios:${NC}"
echo ""
echo "  Production VM (8GB RAM, 4 CPU, Linux)"
echo "    → Recommends: k3s (score: 110)"
echo ""
echo "  macOS Developer Machine"
echo "    → Recommends: minikube (score: 90)"
echo ""
echo "  WSL2 on Windows"
echo "    → Recommends: k3d (score: 90)"
echo ""
echo "  GitHub Actions Runner"
echo "    → Recommends: kind (score: 70)"
echo ""

echo -e "${GREEN}✅ What Gets Installed:${NC}"
echo ""
echo "  1. Optimal Kubernetes cluster for your environment"
echo "  2. PipeOps agent with full RBAC permissions"
echo "  3. Prometheus for metrics collection"
echo "  4. Loki for log aggregation"
echo "  5. Grafana for visualization dashboards"
echo "  6. OpenCost for cost monitoring"
echo "  7. All namespaces and configurations"
echo ""

echo -e "${YELLOW}🔧 Customization:${NC}"
echo ""
echo "  Environment Variables:"
echo "    CLUSTER_TYPE       - Choose cluster type (auto/k3s/minikube/k3d/kind)"
echo "    AUTO_DETECT        - Enable auto-detection (true/false)"
echo "    INSTALL_MONITORING - Install monitoring stack (true/false)"
echo "    CLUSTER_NAME       - Your cluster name"
echo ""

echo -e "${GREEN}📞 Support:${NC}"
echo ""
echo "  • Documentation: https://docs.pipeops.io"
echo "  • Issues: https://github.com/PipeOpsHQ/pipeops-k8-agent/issues"
echo "  • Email: support@pipeops.io"
echo ""
